name: 'Build and Push'
description: 'Build my custom images and push to ghcr.io'

on:
  workflow_dispatch:

  # runs at 0:01 AM UTC on Sundays.
  schedule:
    - cron: '1 0 * * 0'

  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set image name
        id: image-name
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          IMAGE_NAME="${REPO_NAME%-docker}"
          echo "name=${{ github.repository_owner }}/${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ steps.image-name.outputs.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ steps.image-name.outputs.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

